DROP TABLE IF EXISTS PRICE;
CREATE TABLE PRICE (
	
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BRAND_ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRICE_LIST INTEGER NOT NULL,
	PRIORITY INTEGER NOT NULL,
	PRICE FLOAT NOT NULL,
	CURR VARCHAR(255) NOT NULL,
	LAST_UPDATE TIMESTAMP NOT NULL,
	LAST_UPDATE_BY VARCHAR(255) NOT NULL
);
